//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LeanOnMeEntities : DbContext
    {
        public LeanOnMeEntities()
            : base("name=LeanOnMeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminQuestion> AdminQuestions { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<UserQuestion> UserQuestions { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<MenuPage> MenuPages { get; set; }
        public virtual DbSet<DoctorList> DoctorLists { get; set; }
        public virtual DbSet<MyHelper> MyHelpers { get; set; }
        public virtual DbSet<MyMedicine> MyMedicines { get; set; }
        public virtual DbSet<MedicalCondition> MedicalConditions { get; set; }
        public virtual DbSet<MyCallTree> MyCallTrees { get; set; }
        public virtual DbSet<MyNeighbor> MyNeighbors { get; set; }
        public virtual DbSet<MySafePlace> MySafePlaces { get; set; }
    
        public virtual ObjectResult<spLogin_Result> spLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLogin_Result>("spLogin", usernameParameter, passwordParameter);
        }
    }
}
