//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalCondition
    {
        public long MedicalID { get; set; }
        public string CommonName { get; set; }
        public string MedicalName { get; set; }
        public string Description { get; set; }
        public string YearDiagnosed { get; set; }
        public string DoctorDiagnosed { get; set; }
        public string Restrictions { get; set; }
        public Nullable<long> HelperID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Images { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
