//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public long MenuItemID { get; set; }
        public long PageID { get; set; }
        public string MenuItemIcon { get; set; }
        public string MenuItemText { get; set; }
        public string MenuItemLink { get; set; }
        public Nullable<long> MenuItemPosition { get; set; }
    
        public virtual MenuPage MenuPage { get; set; }
    }
}
