//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyMedicine
    {
        public long MedicineID { get; set; }
        public Nullable<long> HelperID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string MedicineName { get; set; }
        public string DosagePerPill { get; set; }
        public string PillsPerDose { get; set; }
        public string Weekdays { get; set; }
        public string TimesTaken { get; set; }
        public string PrescribedDoctor { get; set; }
        public string DoctorContact { get; set; }
        public string Images { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
