//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyNeighbor
    {
        public long NeighborID { get; set; }
        public string Name { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Coordinates { get; set; }
        public string HomeNumber { get; set; }
        public string BusinessNumber { get; set; }
        public string Mobile { get; set; }
        public string Notes { get; set; }
        public Nullable<long> HelperID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Images { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
